print("Welcome to the Python Quiz!\n")
print("I hope this instruction would help you to have the best experience you've had in playing quiz.\n")
print("As you have experienced before clicking the quiz instruction,\nyou would have to sign in first or log in to your account before you can do anything.")
print("After logged in with your new/old account, you can finally play the quiz\nby choosing one of the choices from main menu that you can choose to go to.\n")
print("BUT, you can only type in the number that is assigned based on the description.\ne.g : 1. Play Quiz -- only type the number '1'.\n")
print("Based on the main menu, there are 6 choices that you can choose from the main menu.")
print("1. Play Quiz\n\nPlay Quiz is where you play the quizzes that is made from the users or the developer, combined as one. You would answer it based on the option, such as A, B, C, D, E. A point system would count how many questions you got correct.\n")
print("2. Add Question\n\nAdd Question is where you, as player, add your own quiz for other players or even yourself to do the quiz.\nIt would require a question, choices (min. 2), and the answer based on the option to make it an official question.\n")
print("3. Logout\n\nLogout is where you log out from your current account, and goes back to the first mainmenu where you have to login again.\nThis is not where you want to exit the game.\n")
print("4. See instructions\n\nThis is the instructions so no explanation further.\n")
print("5. Exit\n\nExit, the choice that will end the quiz program and you're finally out from it.\n")
print("6. About us\n\nAbout us, is the description about the quiz maker.")